// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz26l7ln798e6xeomBVqRUxHDxgEa62Bk',
    appId: '1:810225373294:web:f32a46ca2abcd1e32ad67f',
    messagingSenderId: '810225373294',
    projectId: 'synkrama-f7391',
    authDomain: 'synkrama-f7391.firebaseapp.com',
    storageBucket: 'synkrama-f7391.appspot.com',
    measurementId: 'G-DGBYPK3DWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW70CjNJ9bl_sMGOx7IR6It-fVP6aaRVo',
    appId: '1:810225373294:android:6b3dc096b837cd982ad67f',
    messagingSenderId: '810225373294',
    projectId: 'synkrama-f7391',
    storageBucket: 'synkrama-f7391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_OqjS-lCA53JYLnEVwwGrNbPrKdjuAuo',
    appId: '1:810225373294:ios:22de387d2f5cf8152ad67f',
    messagingSenderId: '810225373294',
    projectId: 'synkrama-f7391',
    storageBucket: 'synkrama-f7391.appspot.com',
    iosClientId: '810225373294-1ui9hre0e63bk3s2atmiatg3j8cujcoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.synkrama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_OqjS-lCA53JYLnEVwwGrNbPrKdjuAuo',
    appId: '1:810225373294:ios:d982d7a3d4f30c422ad67f',
    messagingSenderId: '810225373294',
    projectId: 'synkrama-f7391',
    storageBucket: 'synkrama-f7391.appspot.com',
    iosClientId: '810225373294-b4v4p2vaido88gt44kn4du9c7cq129bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.synkrama.RunnerTests',
  );
}
